import { defineConfig } from 'tsup';

export default defineConfig({
    entry: ['src/index.ts'],
    format: ['esm', 'cjs'],
    dts: true,
    sourcemap: true,
    clean: true,
    external: [
        'react',
        'react-native',
        'expo-sqlite',
        '@expo/vector-icons',
        '@shopify/flash-list',
        '@livekit/react-native',
        'livekit-client',
        '@livekit/react-native-webrtc',
        'expo-audio',
        'expo-video',
        'expo-image-picker',
        'expo-document-picker',
        'expo-file-system',
        'expo-file-system/legacy',
        'expo-sharing',
        'expo-intent-launcher',
        '@notifee/react-native',
        '@hongayetu/expo-makachat-push',
        '@gorhom/bottom-sheet',
        'react-native-reanimated',
        'react-native-gesture-handler',
        'react-native-safe-area-context',
        'react-native-keyboard-controller',
    ],
    loader: { '.mp3': 'copy' },
    outExtension: ({ format }) => ({ js: format === 'esm' ? '.js' : '.cjs' }),
});
